spring:
  application:
    name: KinopoiskClient
server:
  port: 8082
springdoc:
  api-docs:
    path: /api-docs
application:
  base-url: /api/v1/movies
kinopoisk-parser:
  base-url: http://localhost:8081/api/v1/movies
